apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmins
  template:
    metadata:
      labels:
        app: phpmyadmins
    spec:
      containers:
        - name: phpmyadmin
          image: phpmyadmin:service
          ports:
            - containerPort: 5000
