apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginxs
  template:
    metadata:
      labels:
        app: nginxs
    spec:
      containers:
        - name: nginxpod
          image: nginx:service
          ports:
            - containerPort: 80