apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginxs
  template:
    metadata:
      labels:
        app: nginxs
    spec:
      containers:
        - name: nginx
          image: nginx:service
          ports:
            - name: port80
              containerPort: 80
            - name: port443
              containerPort: 443
