apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafanas
  template:
    metadata:
      labels:
        app: grafanas
    spec:
      containers:
        - name: grafana
          image: grafana:service
          ports:
            - containerPort: 3000
