#!/bin/sh
kubectl delete -f https://raw.githubusercontent.com/metallb/metallb/v0.9.5/manifests/namespace.yaml
kubectl delete -f https://raw.githubusercontent.com/metallb/metallb/v0.9.5/manifests/metallb.yaml
kubectl delete -f srcs/yaml_config/metallb_config.yaml
kubectl delete -f srcs/yaml_config/volume_config.yaml
kubectl delete -f srcs/yaml_config/Nginx/nginx_deployment.yaml
kubectl delete -f srcs/yaml_config/Nginx/nginx_service.yaml
kubectl delete -f srcs/yaml_config/PhpMyAdmin/phpmyadmin_deployment.yaml
kubectl delete -f srcs/yaml_config/PhpMyAdmin/phpmyadmin_service.yaml
kubectl delete -f srcs/yaml_config/WordPress/wordpress_deployment.yaml
kubectl delete -f srcs/yaml_config/WordPress/wordpress_service.yaml
kubectl delete -f srcs/yaml_config/ftps/ftps_deployment.yaml
kubectl delete -f srcs/yaml_config/ftps/ftps_service.yaml
kubectl delete -f srcs/yaml_config/mysql/mysql_deployment.yaml
kubectl delete -f srcs/yaml_config/mysql/mysql_service.yaml
kubectl delete -f srcs/yaml_config/Grafana/grafana_deployment.yaml
kubectl delete -f srcs/yaml_config/Grafana/grafana_service.yaml
kubectl delete -f srcs/yaml_config/influxDB/influxdb_deployment.yaml
kubectl delete -f srcs/yaml_config/influxDB/influxdb_service.yaml